
const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_KEY || '';
const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${GEMINI_API_KEY}`;

export interface GeneratedContent {
    text: string;
}

export const rewriteNewsArticle = async (title: string, snippet: string, category: string): Promise<string> => {
    if (!GEMINI_API_KEY) {
        console.error("Gemini API Key is missing!");
        return "Error: Gemini API Key is missing.";
    }

    const prompt = `Act as a premium Egyptian Real Estate journalist. Rewrite the following news snippet into a highly engaging, professional social media post. 
    
    Context:
    - Category: ${category}
    - Original Title: ${title}
    - Original Info: ${snippet}

    Guidelines:
    - Format: 2 short, punchy paragraphs.
    - Style: Authoritative, exciting, and insider-focused.
    - **CRITICAL**: If an event, launch, or exhibition is mentioned, extract the Date and Location and list them as bullet points at the bottom.
    - Do not include URLs.`;

    const payload = {
        contents: [{
            parts: [{
                text: prompt
            }]
        }]
    };

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`Gemini API Error: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!generatedText) {
            throw new Error("No content generated by Gemini.");
        }

        return generatedText;

    } catch (error) {
        console.error("Error generating content with Gemini:", error);
        return `Failed to generate content. Original Snippet: ${snippet}`;
    }
};

export const generateJobDescription = async (title: string, company: string, location: string): Promise<string> => {
    if (!GEMINI_API_KEY) return `We are looking for a talented ${title} to join ${company} in ${location}. Apply now!`;

    const prompt = `Write a professional job description for a "${title}" position at "${company}" located in "${location}".
    
    Structure:
    - About the Role (2-3 sentences)
    - Key Responsibilities (4 bullet points)
    - Requirements (3 bullet points)
    - Why Join Us? (1 short sentence)
    
    Tone: Professional, encouraging, and clear. Keep it under 150 words.`;

    const payload = {
        contents: [{ parts: [{ text: prompt }] }]
    };

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) throw new Error("Gemini API Error");

        const data = await response.json();
        return data.candidates?.[0]?.content?.parts?.[0]?.text || `We are looking for a ${title}.`;

    } catch (error) {
        console.error("Error generating job desc:", error);
        return `Join ${company} as a ${title} in ${location}. Great opportunity!`;
    }
};
export const generateJobTemplate = async (jobTitle: string): Promise<{ description: string; requirements: string }> => {
    if (!GEMINI_API_KEY) {
        return {
            description: `We are looking for a talented ${jobTitle} to join our growing team. In this role, you will be responsible for key initiatives and working closely with cross-functional teams to drive success.`,
            requirements: `• Previous experience as a ${jobTitle}\n• Strong communication skills\n• Ability to work in a fast-paced environment\n• Team player mentality`
        };
    }

    const prompt = `Write a professional job description and a bulleted list of requirements for a "${jobTitle}". 
    
    Return the response as a **VALID JSON OBJECT** with exactly two keys: 
    1. 'description' (a short, engaging summary paragraph, max 4 sentences).
    2. 'requirements' (a formatted string of 5-7 bullet points, each on a new line).
    
    Do not include markdown formatting like \`\`\`json. Just return the raw JSON string.`;

    const payload = {
        contents: [{ parts: [{ text: prompt }] }]
    };

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) throw new Error("Gemini API Error");

        const data = await response.json();
        const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!rawText) throw new Error("Empty response from AI");

        // Sanitize and parse JSON
        const jsonString = rawText.replace(/```json|```/g, '').trim();
        const parsed = JSON.parse(jsonString);

        return {
            description: parsed.description || `Join us as a ${jobTitle}.`,
            requirements: parsed.requirements || `• Experience required`
        };

    } catch (error) {
        console.error("Error generating job template:", error);
        // Fallback
        return {
            description: `We are looking for an experienced ${jobTitle} to join our team. You will play a crucial role in our company's success and growth.`,
            requirements: `• Proven experience in ${jobTitle} role\n• Excellent problem-solving skills\n• Strong attention to detail`
        };
    }
};
